import { useState } from 'react'
import { Activity, CheckCircle2, Info, Layers3, Server, Settings2, XCircle } from 'lucide-react'
import { settingsSections } from './settingsRegistry'

type VersionInfo = { version?: string; service?: string }
type Tab = 'overview' | 'system' | 'settings' | 'links'

export function AboutSettings({ version, backendAvailable, sessions }: { version?: VersionInfo; backendAvailable: boolean; sessions: number }) {
  const [activeTab, setActiveTab] = useState<Tab>('overview')
  const service = version?.service || 'nexus-api'
  const versionLabel = version?.version || 'Not reported'

  return <div className="space-y-6">
    <div><h3 className="text-lg font-semibold">About Nexus</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">System identity and diagnostics reported by the connected local runtime. Values that are not exposed by the server are intentionally omitted.</p></div>
    <div className="flex gap-2 border-b border-border">{[['overview', 'Overview'], ['system', 'Runtime'], ['settings', 'Settings map'], ['links', 'Support']].map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id as Tab)} className={`px-4 py-2 text-sm font-medium transition ${activeTab === id ? 'border-b-2 border-foreground text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</div>

    {activeTab === 'overview' && <div className="space-y-5"><div className="rounded-xl border border-border bg-card p-7 text-center"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-primary/10 text-primary"><Info size={30} /></div><h4 className="mt-4 text-2xl font-bold tracking-tight">NEXUS AI</h4><p className="mt-2 text-sm text-muted-foreground">{service} · {versionLabel}</p><div className="mt-5 flex flex-wrap justify-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-secondary px-3 py-1 text-xs font-medium">{backendAvailable ? <CheckCircle2 size={13} className="text-emerald-600" /> : <XCircle size={13} className="text-amber-600" />}{backendAvailable ? 'Backend connected' : 'Backend unavailable'}</span><span className="inline-flex items-center gap-1.5 rounded-full bg-secondary px-3 py-1 text-xs font-medium"><Activity size={13} />{sessions} sessions</span></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><Server size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Runtime service</p><p className="mt-1 font-semibold">{service}</p></div><div className="rounded-lg border border-border bg-card p-4"><Layers3 size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Settings destinations</p><p className="mt-1 font-semibold">{settingsSections.length}</p></div><div className="rounded-lg border border-border bg-card p-4"><Activity size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Session count</p><p className="mt-1 font-semibold">{sessions}</p></div></div></div>}

    {activeTab === 'system' && <div className="rounded-lg border border-border bg-card p-5"><h4 className="text-sm font-semibold">Reported runtime information</h4><dl className="mt-4 divide-y divide-border">{[['Service', service], ['Version', versionLabel], ['Backend', backendAvailable ? 'Connected' : 'Unavailable'], ['Active sessions', String(sessions)]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 py-3 text-sm"><dt className="text-muted-foreground">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl><p className="mt-4 rounded-lg bg-secondary/60 p-3 text-xs text-muted-foreground">Build, framework, test coverage, team, and license metadata are not inferred here because the connected runtime does not report them.</p></div>}

    {activeTab === 'settings' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-start gap-3"><Settings2 size={18} className="mt-0.5 text-primary" /><div><h4 className="text-sm font-semibold">Settings architecture</h4><p className="mt-1 text-sm text-muted-foreground">Nexus exposes {settingsSections.length} purpose-specific Settings destinations grouped by personal preferences, workspace context, runtime, extensions, automation, and system information.</p><div className="mt-4 flex flex-wrap gap-2">{Array.from(new Set(settingsSections.map(section => section.group))).map(group => <span key={group} className="rounded-full bg-secondary px-2.5 py-1 text-xs">{group}</span>)}</div></div></div></div>}

    {activeTab === 'links' && <div className="rounded-lg border border-border bg-card p-5"><h4 className="text-sm font-semibold">Support and diagnostics</h4><p className="mt-1 text-sm text-muted-foreground">Use the Settings navigation to inspect the relevant subsystem. Runtime failures are surfaced on the owning page with the server error and a retry action.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{settingsSections.filter(section => ['Runtime', 'Workspace', 'System'].includes(section.group)).map(section => <div key={section.id} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{section.label}</p><p className="mt-1 text-xs text-muted-foreground">{section.description}</p></div>)}</div></div>}
  </div>
}
