import { useMemo, useState } from 'react'
import { CheckCircle2, CircleAlert, Puzzle, Search, ShieldCheck } from 'lucide-react'
import { type InventoryItem } from '../../lib/api'
import { Description, labelFor } from './utils'

type Tab = 'overview' | 'installed' | 'trust'

export function PluginManager({ items, pending, onToggle }: { items: InventoryItem[]; pending: string; onToggle: (name: string, enabled: boolean) => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('overview')
  const [searchQuery, setSearchQuery] = useState('')
  const trusted = items.filter(item => item.trusted === true).length
  const active = items.filter(item => item.enabled !== false).length
  const filtered = useMemo(() => items.filter(item => !searchQuery.trim() || `${labelFor(item)} ${item.description || ''}`.toLowerCase().includes(searchQuery.toLowerCase())), [items, searchQuery])

  return <div className="space-y-6">
    <div><h3 className="text-lg font-semibold">Plugins</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Review installed extensions and their trust state. Installation, marketplace, and update controls are hidden until Nexus exposes real server actions for them.</p></div>
    <div className="flex gap-2 border-b border-border">{[['overview', 'Overview'], ['installed', 'Installed'], ['trust', 'Trust & availability']].map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id as Tab)} className={`px-4 py-2 text-sm font-medium transition ${activeTab === id ? 'border-b-2 border-foreground text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</div>

    {activeTab === 'overview' && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><Puzzle size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Installed plugins</p><p className="text-2xl font-bold">{items.length}</p></div><div className="rounded-lg border border-border bg-card p-4"><CheckCircle2 size={18} className="text-emerald-600" /><p className="mt-3 text-xs text-muted-foreground">Active</p><p className="text-2xl font-bold">{active}</p></div><div className="rounded-lg border border-border bg-card p-4"><ShieldCheck size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Trusted</p><p className="text-2xl font-bold">{trusted}</p></div></div><div className="rounded-lg border border-border bg-card p-5"><h4 className="text-sm font-semibold">Extension posture</h4><p className="mt-1 text-sm text-muted-foreground">Only the server-reported inventory is shown. Use Installed to change activation state and Trust to inspect what Nexus has verified.</p><button type="button" onClick={() => setActiveTab('installed')} className="mt-4 rounded-md bg-foreground px-3 py-1.5 text-xs text-background">Review installed plugins</button></div></div>}

    {activeTab === 'installed' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Installed extension inventory</h4><p className="mt-1 text-xs text-muted-foreground">Activation changes use the Nexus management API.</p></div><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={searchQuery} onChange={event => setSearchQuery(event.target.value)} placeholder="Search plugins" aria-label="Search plugins" className="h-9 w-56 rounded-md border border-border bg-background pl-9 pr-3 text-sm" /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{filtered.map(item => { const id = String(item.id || item.name || ''); const isEnabled = item.enabled !== false; return <div key={id} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-2"><Puzzle size={16} className="mt-0.5 text-primary" /><div><p className="text-sm font-medium">{labelFor(item)}</p><Description item={item} kind="plugin" /></div></div><button type="button" onClick={() => onToggle(id, !isEnabled)} disabled={pending === id} className={`shrink-0 rounded-md px-2.5 py-1 text-xs font-medium disabled:opacity-50 ${isEnabled ? 'bg-foreground text-background' : 'border border-border text-muted-foreground'}`}>{pending === id ? 'Saving…' : isEnabled ? 'On' : 'Off'}</button></div><div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-secondary px-2 py-0.5">{isEnabled ? 'Active' : 'Inactive'}</span><span className="rounded-full bg-secondary px-2 py-0.5">{item.available === false ? 'Unavailable' : 'Available'}</span>{item.trusted === true && <span className="rounded-full bg-secondary px-2 py-0.5">Trusted</span>}</div></div>})}{!filtered.length && <div className="col-span-full rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No installed plugins were reported.</div>}</div></div>}

    {activeTab === 'trust' && <div className="space-y-4"><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-start gap-3"><ShieldCheck size={18} className="mt-0.5 text-primary" /><div><h4 className="text-sm font-semibold">Trust and availability</h4><p className="mt-1 text-sm text-muted-foreground">These values are read from plugin inventory metadata. Plugin installation, updates, and trust changes are not available through the current Settings API.</p></div></div></div><div className="divide-y divide-border rounded-lg border border-border">{items.map(item => <div key={String(item.id || item.name)} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">{labelFor(item)}</p><p className="mt-1 text-xs text-muted-foreground">{item.trusted === true ? 'Trusted by Nexus' : 'Trust not reported'} · {item.available === false ? 'Unavailable' : 'Available'}</p></div>{item.trusted === true ? <CheckCircle2 size={17} className="text-emerald-600" /> : <CircleAlert size={17} className="text-amber-600" />}</div>)}</div></div>}
  </div>
}
