import { useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, CircleAlert, GraduationCap, Search, Tags } from 'lucide-react'
import { type InventoryItem } from '../../lib/api'
import { Description, labelFor } from './utils'

type Tab = 'overview' | 'installed' | 'categories' | 'settings'

export function SkillsManager({ items, pending, onToggle }: { items: InventoryItem[]; pending: string; onToggle: (name: string, enabled: boolean) => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('overview')
  const [searchQuery, setSearchQuery] = useState('')
  const categories = useMemo(() => Array.from(new Set(items.map(item => String(item.category || 'General')))).sort(), [items])
  const filteredItems = useMemo(() => items.filter(item => !searchQuery.trim() || `${labelFor(item)} ${item.description || ''} ${item.category || ''}`.toLowerCase().includes(searchQuery.toLowerCase())), [items, searchQuery])
  const enabled = items.filter(item => item.enabled !== false).length

  return <div className="space-y-6">
    <div><h3 className="text-lg font-semibold">Skills</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Inspect the capability library Nexus can use. Enable or disable skills from the server-reported inventory; unsupported policy controls are intentionally not presented as saved settings.</p></div>
    <div className="flex gap-2 border-b border-border">{[
      ['overview', 'Overview'], ['installed', 'Inventory'], ['categories', 'Categories'], ['settings', 'Policy'],
    ].map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id as Tab)} className={`px-4 py-2 text-sm font-medium transition ${activeTab === id ? 'border-b-2 border-foreground text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</div>

    {activeTab === 'overview' && <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-3">
        <div className="rounded-lg border border-border bg-card p-4"><GraduationCap size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Installed skills</p><p className="text-2xl font-bold">{items.length}</p></div>
        <div className="rounded-lg border border-border bg-card p-4"><CheckCircle2 size={18} className="text-emerald-600" /><p className="mt-3 text-xs text-muted-foreground">Enabled</p><p className="text-2xl font-bold">{enabled}</p></div>
        <div className="rounded-lg border border-border bg-card p-4"><Tags size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Categories</p><p className="text-2xl font-bold">{categories.length}</p></div>
      </div>
      <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Capability inventory</h4><p className="mt-1 text-xs text-muted-foreground">Live items returned by the Nexus server.</p></div><button type="button" onClick={() => setActiveTab('installed')} className="rounded-md border border-border px-3 py-1.5 text-xs">Open inventory</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{items.slice(0, 4).map(item => <div key={String(item.id || item.name)} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{labelFor(item)}</p><Description item={item} kind="skill" /><span className="mt-2 inline-flex rounded-full bg-secondary px-2 py-0.5 text-[11px]">{item.enabled === false ? 'Disabled' : 'Enabled'}</span></div>)}{!items.length && <p className="text-sm text-muted-foreground">No skills were reported.</p>}</div></div>
    </div>}

    {activeTab === 'installed' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Installed skill inventory</h4><p className="mt-1 text-xs text-muted-foreground">Search by name, description, or category.</p></div><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={searchQuery} onChange={event => setSearchQuery(event.target.value)} placeholder="Search skills" aria-label="Search skills" className="h-9 w-64 rounded-md border border-border bg-background pl-9 pr-3 text-sm" /></div></div><div className="mt-4 divide-y divide-border rounded-lg border border-border">{filteredItems.map(item => { const id = String(item.id || item.name || ''); const isEnabled = item.enabled !== false; return <div key={id} className="flex items-start gap-3 p-4"><span className="mt-0.5">{isEnabled ? <CheckCircle2 size={16} className="text-emerald-600" /> : <CircleAlert size={16} className="text-amber-600" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{labelFor(item)}</p><span className="rounded-full bg-secondary px-2 py-0.5 text-[11px]">{String(item.category || 'General')}</span></div><Description item={item} kind="skill" /></div><button type="button" onClick={() => onToggle(id, !isEnabled)} disabled={pending === id} className={`shrink-0 rounded-md px-2.5 py-1 text-xs font-medium disabled:opacity-50 ${isEnabled ? 'bg-foreground text-background' : 'border border-border text-muted-foreground'}`}>{pending === id ? 'Saving…' : isEnabled ? 'On' : 'Off'}</button></div>})}{!filteredItems.length && <div className="p-8 text-center"><BookOpen size={32} className="mx-auto text-muted-foreground" /><p className="mt-3 text-sm font-medium">No matching skills</p><p className="mt-1 text-xs text-muted-foreground">Try a different search.</p></div>}</div></div>}

    {activeTab === 'categories' && <div className="grid gap-4 sm:grid-cols-2">{categories.map(category => { const categoryItems = items.filter(item => String(item.category || 'General') === category); return <div key={category} className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h4 className="text-sm font-semibold">{category}</h4><p className="mt-1 text-xs text-muted-foreground">{categoryItems.length} reported skill{categoryItems.length === 1 ? '' : 's'}</p></div><Tags size={18} className="text-primary" /></div><div className="mt-4 flex flex-wrap gap-2">{categoryItems.map(item => <span key={String(item.id || item.name)} className="rounded-full bg-secondary px-2.5 py-1 text-xs">{labelFor(item)}</span>)}</div></div>})}{!categories.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Categories appear when the server reports skills.</div>}</div>}

    {activeTab === 'settings' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-start gap-3"><BookOpen size={18} className="mt-0.5 text-primary" /><div><h4 className="text-sm font-semibold">Server-managed skill policy</h4><p className="mt-1 text-sm text-muted-foreground">Nexus currently exposes skill availability and enable/disable state through the inventory API. Execution limits, chaining, learning, and logging preferences are not persisted by the available API, so there are no misleading unsaved controls here.</p></div></div></div>}
  </div>
}
