import { useMemo, useState } from 'react'
import { CheckCircle2, CircleAlert, Filter, Hammer, Search, ShieldCheck } from 'lucide-react'
import { type InventoryItem } from '../../lib/api'
import { Description, labelFor } from './utils'

type Tab = 'overview' | 'registered' | 'categories' | 'settings'

export function ToolsManager({ items, pending, onToggle }: { items: InventoryItem[]; pending: string; onToggle: (name: string, enabled: boolean) => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('overview')
  const [searchQuery, setSearchQuery] = useState('')
  const [categoryFilter, setCategoryFilter] = useState('all')
  const categories = useMemo(() => Array.from(new Set(items.map(item => String(item.category || 'General')))).sort(), [items])
  const filteredItems = useMemo(() => items.filter(item => {
    const text = `${labelFor(item)} ${item.description || ''} ${item.category || ''}`.toLowerCase()
    return (!searchQuery.trim() || text.includes(searchQuery.toLowerCase())) && (categoryFilter === 'all' || String(item.category || 'General') === categoryFilter)
  }), [items, searchQuery, categoryFilter])
  const enabled = items.filter(item => item.enabled !== false).length
  const readOnly = items.filter(item => item.read_only === true).length
  const safe = items.filter(item => item.safe === true).length

  return <div className="space-y-6">
    <div><h3 className="text-lg font-semibold">Tools</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Manage the operations Nexus can invoke. Tool metadata, safety flags, and availability below come from the live registry.</p></div>
    <div className="flex gap-2 border-b border-border">{[['overview', 'Overview'], ['registered', 'Registry'], ['categories', 'Categories'], ['settings', 'Policy']].map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id as Tab)} className={`px-4 py-2 text-sm font-medium transition ${activeTab === id ? 'border-b-2 border-foreground text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</div>

    {activeTab === 'overview' && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border border-border bg-card p-4"><Hammer size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Registered tools</p><p className="text-2xl font-bold">{items.length}</p></div><div className="rounded-lg border border-border bg-card p-4"><CheckCircle2 size={18} className="text-emerald-600" /><p className="mt-3 text-xs text-muted-foreground">Enabled</p><p className="text-2xl font-bold">{enabled}</p></div><div className="rounded-lg border border-border bg-card p-4"><ShieldCheck size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Read-only / safe</p><p className="text-2xl font-bold">{readOnly} / {safe}</p></div><div className="rounded-lg border border-border bg-card p-4"><Filter size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Categories</p><p className="text-2xl font-bold">{categories.length}</p></div></div><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Registry health</h4><p className="mt-1 text-xs text-muted-foreground">Use the registry to inspect real tool metadata and change availability.</p></div><button type="button" onClick={() => setActiveTab('registered')} className="rounded-md border border-border px-3 py-1.5 text-xs">Open registry</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{items.slice(0, 4).map(item => <div key={String(item.id || item.name)} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{labelFor(item)}</p><Description item={item} kind="tool" /><div className="mt-2 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-secondary px-2 py-0.5">{item.enabled === false ? 'Disabled' : 'Enabled'}</span>{item.read_only === true && <span className="rounded-full bg-secondary px-2 py-0.5">Read-only</span>}{item.safe === true && <span className="rounded-full bg-secondary px-2 py-0.5">Safe</span>}</div></div>)}{!items.length && <p className="text-sm text-muted-foreground">No tools were reported.</p>}</div></div></div>}

    {activeTab === 'registered' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Registered tool registry</h4><p className="mt-1 text-xs text-muted-foreground">Filter by capability or server-reported category.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={searchQuery} onChange={event => setSearchQuery(event.target.value)} placeholder="Search tools" aria-label="Search tools" className="h-9 w-56 rounded-md border border-border bg-background pl-9 pr-3 text-sm" /></div><select value={categoryFilter} onChange={event => setCategoryFilter(event.target.value)} aria-label="Tool category" className="h-9 rounded-md border border-border bg-background px-3 text-sm"><option value="all">All categories</option>{categories.map(category => <option key={category} value={category}>{category}</option>)}</select></div></div><div className="mt-4 divide-y divide-border rounded-lg border border-border">{filteredItems.map(item => { const id = String(item.id || item.name || ''); const isEnabled = item.enabled !== false; return <div key={id} className="flex items-start gap-3 p-4"><span className="mt-0.5">{isEnabled ? <CheckCircle2 size={16} className="text-emerald-600" /> : <CircleAlert size={16} className="text-amber-600" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{labelFor(item)}</p>{item.read_only === true && <span className="rounded-full bg-secondary px-2 py-0.5 text-[11px]">Read-only</span>}{item.safe === true && <span className="rounded-full bg-secondary px-2 py-0.5 text-[11px]">Safe</span>}</div><Description item={item} kind="tool" /></div><button type="button" onClick={() => onToggle(id, !isEnabled)} disabled={pending === id} className={`shrink-0 rounded-md px-2.5 py-1 text-xs font-medium disabled:opacity-50 ${isEnabled ? 'bg-foreground text-background' : 'border border-border text-muted-foreground'}`}>{pending === id ? 'Saving…' : isEnabled ? 'On' : 'Off'}</button></div>})}{!filteredItems.length && <div className="p-8 text-center text-sm text-muted-foreground">No matching tools.</div>}</div></div>}

    {activeTab === 'categories' && <div className="grid gap-4 sm:grid-cols-2">{categories.map(category => { const categoryItems = items.filter(item => String(item.category || 'General') === category); return <button type="button" key={category} onClick={() => { setCategoryFilter(category); setActiveTab('registered') }} className="rounded-lg border border-border bg-card p-5 text-left hover:border-primary/50"><div className="flex items-center justify-between"><div><h4 className="text-sm font-semibold">{category}</h4><p className="mt-1 text-xs text-muted-foreground">{categoryItems.length} tool{categoryItems.length === 1 ? '' : 's'}</p></div><Filter size={18} className="text-primary" /></div><div className="mt-4 flex flex-wrap gap-2">{categoryItems.map(item => <span key={String(item.id || item.name)} className="rounded-full bg-secondary px-2.5 py-1 text-xs">{labelFor(item)}</span>)}</div></button>})}{!categories.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Categories appear when the registry reports tools.</div>}</div>}

    {activeTab === 'settings' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-start gap-3"><ShieldCheck size={18} className="mt-0.5 text-primary" /><div><h4 className="text-sm font-semibold">Execution policy</h4><p className="mt-1 text-sm text-muted-foreground">The available Settings API exposes tool enable/disable state and server-reported safety metadata. Per-tool permission rules and runtime limits are controlled by the Safety and Configuration pages.</p></div></div></div>}
  </div>
}
