import math
from typing import List, Any

class NexusMath:
    """
    NEXUS MATH LIBRARY 1.0
    Generated by NEXUS AI Core Reasoning.
    
    Features:
    - Geometric Mean calculation.
    - Standard Deviation calculation.
    - Precision Vector-Proofed.
    """
    
    @staticmethod
    def geometric_mean(numbers: List[Any]) -> float:
        """Calculates the product of numbers raised to the power of 1/n."""
        if not numbers: return 0.0
        product = math.prod(numbers)
        return math.pow(product, 1/len(numbers))
        
    @staticmethod
    def standard_deviation(numbers: List[Any]) -> float:
        """Calculates the amount of variation or dispersion of a set of values."""
        if len(numbers) < 2: return 0.0
        mean = sum(numbers) / len(numbers)
        variance = sum((x - mean) ** 2 for x in numbers) / len(numbers)
        return math.sqrt(variance)

if __name__ == "__main__":
    nums = [2, 8, 10, 32]
    print(f"Numbers: {nums}")
    print(f"Geometric Mean: {NexusMath.geometric_mean(nums)}")
    print(f"Standard Deviation: {NexusMath.standard_deviation(nums)}")
