export function Appearance({ theme, onTheme }: { theme: string; onTheme: (theme: string) => void }) {
  const options = [
    { value: 'light', label: 'Light', detail: 'Bright, clean workspace', bg: 'bg-white', dotDark: 'bg-gray-900', dotMid: 'bg-gray-300', dotLight: 'bg-gray-100' },
    { value: 'dark', label: 'Dark', detail: 'Low-light, easy on the eyes', bg: 'bg-gray-900', dotDark: 'bg-gray-100', dotMid: 'bg-gray-500', dotLight: 'bg-gray-700' },
    { value: 'grey', label: 'Grey', detail: 'Neutral grey tones', bg: 'bg-gray-100', dotDark: 'bg-gray-700', dotMid: 'bg-gray-400', dotLight: 'bg-gray-200' },
    { value: 'glass', label: 'Glass', detail: 'Translucent soft overlay', bg: 'bg-white/40', dotDark: 'bg-sky-300', dotMid: 'bg-white/60', dotLight: 'bg-sky-100' },
    { value: 'green', label: 'Green', detail: 'Calming green palette', bg: 'bg-green-900', dotDark: 'bg-green-100', dotMid: 'bg-green-400', dotLight: 'bg-green-700' },
    { value: 'blue', label: 'Blue', detail: 'Cool blue workspace', bg: 'bg-blue-900', dotDark: 'bg-blue-100', dotMid: 'bg-blue-400', dotLight: 'bg-blue-700' },
    { value: 'purple', label: 'Purple', detail: 'Creative purple mode', bg: 'bg-purple-900', dotDark: 'bg-purple-100', dotMid: 'bg-purple-400', dotLight: 'bg-purple-700' },
    { value: 'pink', label: 'Pink', detail: 'Soft pink accents', bg: 'bg-pink-900', dotDark: 'bg-pink-100', dotMid: 'bg-pink-400', dotLight: 'bg-pink-700' },
    { value: 'red', label: 'Red', detail: 'Bold red highlights', bg: 'bg-red-900', dotDark: 'bg-red-100', dotMid: 'bg-red-400', dotLight: 'bg-red-700' },
    { value: 'orange', label: 'Orange', detail: 'Warm orange tones', bg: 'bg-orange-900', dotDark: 'bg-orange-100', dotMid: 'bg-orange-400', dotLight: 'bg-orange-700' },
  ] as const
  return <div className="space-y-6"><div><h3 className="text-sm font-semibold">Color theme</h3><p className="mt-1 text-sm text-muted-foreground">Choose how Nexus looks in this browser. Themes apply instantly and are saved to this device.</p></div><div className="grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-3">{options.map(choice => <button key={choice.value} onClick={() => onTheme(choice.value)} className={`rounded-xl border p-4 text-left transition hover:border-foreground/60 ${theme === choice.value ? 'border-foreground bg-secondary ring-1 ring-foreground/25' : 'border-border'}`}><div className={`mb-3 flex items-center gap-1.5 rounded-lg border border-border/70 px-2 py-1.5 ${choice.bg}`}><span className={`h-3 w-3 rounded-full ${choice.dotDark}`} /><span className={`h-3 w-3 rounded-full ${choice.dotMid}`} /><span className={`h-3 w-3 rounded-full ${choice.dotLight}`} /></div><p className="font-medium capitalize">{choice.label}</p><p className="mt-1 text-xs text-muted-foreground">{choice.detail}</p>{theme === choice.value && <span className="mt-2 inline-flex items-center gap-1.5 text-[11px] font-medium text-emerald-700 dark:text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-current" />Active</span>}</button>)}</div></div>
}
