import { useState, type FormEvent } from 'react'
import { Activity, Code2, Network, Plus, Terminal, Trash2 } from 'lucide-react'
import { api, type InventoryItem } from '../../lib/api'
import { Description } from './utils'

type Tab = 'overview' | 'servers' | 'add' | 'diagnostics'

export function McpManager({ items, pending, onToggle, onChanged, onError }: { items: InventoryItem[]; pending: string; onToggle: (name: string, enabled: boolean) => void; onChanged: () => void; onError: (message: string) => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('overview')
  const [name, setName] = useState(''); const [command, setCommand] = useState(''); const [args, setArgs] = useState(''); const [description, setDescription] = useState(''); const [envVars, setEnvVars] = useState(''); const [workingDir, setWorkingDir] = useState(''); const [saving, setSaving] = useState(false)
  const active = items.filter(item => item.active === true).length
  const toolCount = items.reduce((sum, item) => sum + (Array.isArray(item.tools) ? item.tools.length : 0), 0)
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true); onError('')
    try {
      const env = envVars.trim() ? JSON.parse(envVars) : undefined
      await api.createMcp({ name, command, args: args.split(/\r?\n/).map(value => value.trim()).filter(Boolean), description, active: true, env, working_dir: workingDir || undefined })
      setName(''); setCommand(''); setArgs(''); setDescription(''); setEnvVars(''); setWorkingDir(''); onChanged(); setActiveTab('servers')
    } catch (err) { onError(err instanceof Error ? err.message : 'Could not add the MCP server.') } finally { setSaving(false) }
  }
  const remove = async (id: string) => { if (!window.confirm(`Delete MCP server "${id}"?`)) return; try { await api.deleteMcp(id); onChanged() } catch (err) { onError(err instanceof Error ? err.message : 'Could not delete the MCP server.') } }

  return <div className="space-y-6">
    <div><h3 className="text-lg font-semibold">MCP servers</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Connect external Model Context Protocol servers and inspect the tools they expose. Every server shown below comes from the Nexus MCP inventory.</p></div>
    <div className="flex gap-2 border-b border-border">{[['overview', 'Overview'], ['servers', 'Servers'], ['add', 'Add server'], ['diagnostics', 'Diagnostics']].map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id as Tab)} className={`px-4 py-2 text-sm font-medium transition ${activeTab === id ? 'border-b-2 border-foreground text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</div>

    {activeTab === 'overview' && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><Network size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Configured servers</p><p className="text-2xl font-bold">{items.length}</p></div><div className="rounded-lg border border-border bg-card p-4"><Activity size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Active connections</p><p className="text-2xl font-bold">{active}</p></div><div className="rounded-lg border border-border bg-card p-4"><Code2 size={18} className="text-primary" /><p className="mt-3 text-xs text-muted-foreground">Reported tools</p><p className="text-2xl font-bold">{toolCount}</p></div></div><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Connection inventory</h4><p className="mt-1 text-xs text-muted-foreground">MCP health and response telemetry are only shown when the server reports them.</p></div><button type="button" onClick={() => setActiveTab('add')} className="inline-flex items-center gap-2 rounded-md bg-foreground px-3 py-1.5 text-xs text-background"><Plus size={14} /> Add server</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{items.slice(0, 4).map(item => <div key={String(item.id || item.name)} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">{String(item.name || item.id || 'MCP server')}</p><Description item={item} kind="mcp" /><p className="mt-2 text-xs text-muted-foreground">{Array.isArray(item.tools) ? `${item.tools.length} reported tools` : 'Tool count not reported'}</p></div>)}{!items.length && <p className="text-sm text-muted-foreground">No MCP servers are configured.</p>}</div></div></div>}

    {activeTab === 'servers' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h4 className="text-sm font-semibold">Configured servers</h4><p className="mt-1 text-xs text-muted-foreground">Enable, disable, inspect, or remove a server.</p></div><button type="button" onClick={() => setActiveTab('add')} className="inline-flex items-center gap-2 rounded-md bg-foreground px-3 py-1.5 text-xs text-background"><Plus size={14} /> Add server</button></div><div className="mt-4 space-y-3">{items.map(item => { const id = String(item.id || item.name || ''); const isActive = item.active === true; const tools = Array.isArray(item.tools) ? item.tools.length : 0; return <div key={id} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Network size={16} className="text-primary" /><p className="text-sm font-semibold">{id}</p><span className="rounded-full bg-secondary px-2 py-0.5 text-[11px]">{isActive ? 'Active' : 'Inactive'}</span></div><p className="mt-2 font-mono text-xs text-muted-foreground">{String(item.command || 'Command not reported')}</p><Description item={item} kind="mcp" /><p className="mt-1 text-xs text-muted-foreground">{tools} reported tools{Array.isArray(item.args) && item.args.length ? ` · ${item.args.map(String).join(' ')}` : ''}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={() => onToggle(id, !isActive)} disabled={pending === id} className={`rounded-md px-2.5 py-1 text-xs font-medium disabled:opacity-50 ${isActive ? 'bg-foreground text-background' : 'border border-border text-muted-foreground'}`}>{pending === id ? 'Saving…' : isActive ? 'On' : 'Off'}</button><button type="button" onClick={() => void remove(id)} className="rounded-md border border-destructive/30 p-1.5 text-destructive" aria-label={`Delete ${id}`}><Trash2 size={14} /></button></div></div></div>})}{!items.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No MCP servers are configured.</div>}</div></div>}

    {activeTab === 'add' && <form onSubmit={submit} className="space-y-4 rounded-lg border border-border bg-card p-5"><div><h4 className="text-sm font-semibold">Register an MCP server</h4><p className="mt-1 text-xs text-muted-foreground">This form writes a real server definition through the Nexus MCP API.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Name<input required value={name} onChange={event => setName(event.target.value)} className="h-10 rounded-md border border-border bg-background px-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-sm font-medium">Command<input required value={command} onChange={event => setCommand(event.target.value)} placeholder="python" className="h-10 rounded-md border border-border bg-background px-3 font-mono text-sm font-normal" /></label><label className="grid gap-1.5 text-sm font-medium">Arguments<textarea value={args} onChange={event => setArgs(event.target.value)} placeholder="One argument per line" className="min-h-24 rounded-md border border-border bg-background p-3 font-mono text-sm font-normal" /></label><label className="grid gap-1.5 text-sm font-medium">Working directory<input value={workingDir} onChange={event => setWorkingDir(event.target.value)} className="h-10 rounded-md border border-border bg-background px-3 text-sm font-normal" /></label></div><label className="grid gap-1.5 text-sm font-medium">Description<textarea value={description} onChange={event => setDescription(event.target.value)} className="min-h-20 rounded-md border border-border bg-background p-3 text-sm font-normal" /></label><label className="grid gap-1.5 text-sm font-medium">Environment variables <span className="text-xs font-normal text-muted-foreground">JSON object, optional</span><textarea value={envVars} onChange={event => setEnvVars(event.target.value)} placeholder={'{"TOKEN":"..."}'} className="min-h-20 rounded-md border border-border bg-background p-3 font-mono text-sm font-normal" /></label><div className="flex justify-end"><button type="submit" disabled={saving} className="rounded-md bg-foreground px-4 py-2 text-sm text-background disabled:opacity-50">{saving ? 'Adding…' : 'Add server'}</button></div></form>}

    {activeTab === 'diagnostics' && <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-start gap-3"><Terminal size={18} className="mt-0.5 text-primary" /><div><h4 className="text-sm font-semibold">MCP diagnostics</h4><p className="mt-1 text-sm text-muted-foreground">The current server API provides configuration and activation operations, but no connection-test or per-server log endpoint. The page therefore avoids presenting non-functional test buttons.</p></div></div></div>}
  </div>
}
